"""initial migration

Revision ID: d74d957bdb9d
Revises: 
Create Date: 2025-02-04 16:28:49.841554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74d957bdb9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('preferencias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('pasos', sa.Integer(), nullable=True),
    sa.Column('calorias', sa.Float(), nullable=True),
    sa.Column('distancia', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_id'), 'actividades', ['id'], unique=False)
    op.create_index(op.f('ix_actividades_tipo'), 'actividades', ['tipo'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(), nullable=False),
    sa.Column('respuesta', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_table('salud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frecuencia_cardiaca', sa.Float(), nullable=True),
    sa.Column('calidad_sueno', sa.Float(), nullable=True),
    sa.Column('nivel_estres', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salud_id'), 'salud', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salud_id'), table_name='salud')
    op.drop_table('salud')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_actividades_tipo'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_id'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
